### ISSUE TITLE
runtime data corruption

### ISSUE THREAD

**Issue by KampfCaspar** [wdonne/traefikoidc#9]
Hi!

With the current version 1.2.1 I reproducibly have the situation where a login works well immediately after (re)start, but after some hours, it only results in:

`token signature is invalid: crypto/rsa: verification error`

My config is rather minimal:
   
```
    plugin:
        oidcclient:
          encryptionSecretFile: /etc/traefik/encryption_secret.json
          idps:
            - name: default
              providerUrl: "https://XXXX/"
              postLogoutUrl: "https://XXXX/"
              clientSecretFile: /etc/traefik/oidc_secrets.json
              scopes:
                - openid
                - portal
```
